Adding the execution part in the start stop restart commands
LDuheron/Taskmaster pull request #10
Opened 2024-06-17 13:26 UTC by LDuheron

2024-06-17 14:08 UTC, tsiguenz requested changes
Good job, some things to change but it's pretty :)

2024-06-17 14:08 UTC, tsiguenz commented on src/parser/job.rs
> +                }
use args

2024-06-17 14:08 UTC, tsiguenz commented on src/parser/job.rs
> +                        continue;
do this ealier

2024-06-17 14:08 UTC, tsiguenz commented on src/parser/job.rs
> +                        continue;
don't need to try wait because if the child exist, the process is running

2024-06-17 14:08 UTC, tsiguenz commented on src/parser/job.rs
> +                    command.env(key, value);
can use envs

2024-06-17 14:08 UTC, tsiguenz commented on src/parser/job.rs
> +                    eprintln!("Error: {:?}", work_dir);
https://doc.rust-lang.org/std/path/struct.Path.html#method.is_dir 
use is_dir to check if the path is a directory

2024-06-19 12:40 UTC, LDuheron commented
addd comments for the hashmap modifications, check start / stop + modify name of variable

2024-06-20 14:57 UTC, tsiguenz approved these changes

2024-06-20 15:01 UTC, merged